steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gce-mcp-frontend', '-f', 'Dockerfile.frontend', '.']
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gce-mcp-frontend'
